### ISSUE TITLE
Plugin is always active, and slows down Visual Studio when using SVN

### ISSUE THREAD

**Issue by ktw** [yysun/git-tools#2]
When the Git-Tools extension is enabled, and Visual Studio is working with projects controlled by SVN, the system becomes very unresponsive.
Changing tabs and scrolling is very slow, and the code editor has major lag.

A look in SysInternals Process Monitor (procmon.exe) shows some slow actions, related to missing .git files. -> http://technet.microsoft.com/da-dk/sysinternals/bb896645.aspx

After disabling the Git-Tools extension, Visual Studio is back to normal.

**Comment by yysun** [comment]
The tool checks the project folder for git status changes as soon as any file is modified. It does that  even with none git controlled project, so that it can detect git repository initialization/deletion. Usually Visual Studio doesn't modify the files in project folder without user saving them. Maybe in cases of SVN, there is another background process writes to the project folder that triggers the git tool run.

I can add a configuration settings to disable the file modification checking.

**Comment by ktw** [comment]
I see what you mean.
If the automatic check for git repository initialization was a configurable option, I think the problem would be solved.
Wouldn't initialization be picked up, if the user presses the refresh button, in the Git-Tools window?

Btw, great work you have done with these extensions!

**Comment by yysun** [comment]
After auto checking is disabled, user will have to click the refresh button to see if git is initialized.

**Comment by ktw** [comment]
Let me know, if you want me to test something.
